# KNN 알고리즘 구현

### 데이터 불러오기: Iris

In [437]:
from sklearn.datasets import load_iris

iris_=load_iris()
iris={'data':iris_['data'],'target':iris_['target']}
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

### 훈련용 데이터와 테스트용 데이터로 분리

In [438]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(iris['data'],iris['target'],stratify=iris['target'])

### 학습: 데이터 저장

In [439]:
train={'data':train_data,'target':train_target}

In [440]:
#함수로 저장
def fit(train_data,train_target):
    train={'data':train_data,'target':train_target}

### 예측

- 각 데이터까지의 거리 구하기

In [441]:
import numpy as np

def dist(x,y):
    return np.sqrt(np.sum([(m2-m1)**2 for (m1,m2) in zip(x,y)]))

In [442]:
test_data[2]

array([5.6, 3. , 4.1, 1.3])

In [443]:
dlist={'dist':[],'target':[]}

for d,t in zip(train['data'],train['target']):
    dlist['dist'].append(dist(test_data[2],d))
    dlist['target'].append(t)

In [444]:
dlist

{'dist': [2.9698484809834995,
  0.5477225575051655,
  0.1732050807568884,
  2.3727621035409348,
  2.7221315177632395,
  1.3820274961085255,
  3.0886890422961,
  2.677685567799176,
  1.8493242008906934,
  1.0488088481701519,
  2.882707061079915,
  0.5744562646538027,
  0.469041575982343,
  0.1732050807568884,
  3.0675723300355937,
  0.5477225575051662,
  2.0099751242241783,
  2.891366458960192,
  0.4472135954999582,
  3.082207001484488,
  1.5394804318340658,
  2.796426290821912,
  1.191637528781299,
  1.2845232578665131,
  2.1213203435596433,
  1.2206555615733703,
  2.9647934160747185,
  1.0677078252031316,
  1.5842979517754865,
  3.036445290137795,
  1.0954451150103326,
  2.8478061731796283,
  0.5099019513592781,
  1.1224972160321824,
  2.7110883423451915,
  1.7320508075688774,
  1.7916472867168922,
  1.9339079605813718,
  0.7937253933193776,
  2.924038303442689,
  2.1633307652783937,
  1.5297058540778357,
  3.1543620591175006,
  0.4898979485566356,
  2.91547594742265,
  0.812403840463

### 가장 가까운 점 3개 추출

In [445]:
np.argsort(dlist['dist'][:3])

array([2, 1, 0], dtype=int64)

In [446]:
n3_neighbors=[dlist['target'][a] for a in np.array(dlist['dist']).argsort()[:3]]

In [447]:
n3_neighbors

[1, 1, 1]

### 가장 개수가 많은 타겟 찾기

In [448]:
np.unique(n3_neighbors,return_counts=True)[0][np.argmax(np.unique(n3_neighbors,return_counts=True)[1])]

1

### 실제 값과 비교

In [449]:
test_target[2]

1

In [450]:
#함수로 저장
def predict(data):
    return_list=[]

    for dt in data:
        d_list={'dist':[],'target':[]}
        for d,t in zip(train['data'],train['target']):
            d_list['dist'].append(dist(dt,d))
            d_list['target'].append(t)
    
        n_neighbors=[d_list['target'][a] for a in np.argsort(d_list['dist'][:3])]
        print(n_neighbors)
        return_list.append(np.unique(n_neighbors,return_counts=True)[0][np.argmax(np.unique(n_neighbors,return_counts=True)[1])])
    
    return return_list

In [451]:
predict(test_data)

[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[0, 1, 1]
[0, 1, 1]
[0, 1, 1]
[0, 1, 1]
[1, 1, 0]
[0, 1, 1]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[0, 1, 1]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[0, 1, 1]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[0, 1, 1]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[0, 1, 1]
[1, 1, 0]
[0, 1, 1]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[1, 1, 0]
[0, 1, 1]
[0, 1, 1]
[0, 1, 1]
[1, 1, 0]
[1, 1, 0]


[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [452]:
test_target

array([1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 2, 0, 2,
       1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 2, 0, 0, 0, 2, 2])

In [453]:
class MyKNNClassifier:
    n_neighbors=3
    train={}

    def __init__(self,n_neighbors=3):
        self.n_neighbors=n_neighbors

    def fit(self,train_data,train_target):
        self.train['data']=train_data
        self.train['target']=train_target
    
    def _dist(self,x,y):
        return np.sqrt(np.sum([(m2-m1)**2 for (m1,m2) in zip(x,y)]))

    def predict(self,data):
        return_list=[]

        for dt in data:
            d_list={'dist':[],'target':[]}
            for d,t in zip(self.train['data'],self.train['target']):
                d_list['dist'].append(self._dist(dt,d))
                d_list['target'].append(t)
    
            n_neighbors=[d_list['target'][a] for a in np.array(d_list['dist']).argsort()[:3]]
            return_list.append(np.unique(n_neighbors,return_counts=True)[0][np.argmax(np.unique(n_neighbors,return_counts=True)[1])])
    
        return return_list

    def score(self,data,target):
        predicted=self.predict(data)
        score_list=[a==b for a,b in zip(predicted,target)]
        return np.mean(score_list)


In [454]:
mknn=MyKNNClassifier(n_neighbors=3)
mknn.fit(train_data,train_target)
mknn.score(test_data,test_target)

0.9736842105263158

### sklearn과 비교

In [455]:
mknn=MyKNNClassifier(n_neighbors=3)
mknn.fit(train_data,train_target)
mknn.score(test_data,test_target)

0.9736842105263158

In [456]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(train_data,train_target)
knn.score(test_data,test_target)

0.9736842105263158